"""add language framework and description to project

Revision ID: c4ec5c9bd199
Revises: 1598f8581815
Create Date: 2026-01-05 10:27:01.801640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ec5c9bd199'
down_revision = '1598f8581815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('language', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('framework', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'framework')
    op.drop_column('projects', 'language')
    # ### end Alembic commands ###

