"""Debug AI initial migration

Revision ID: da130b95b66f
Revises: 
Create Date: 2025-12-23 12:53:31.749901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da130b95b66f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_key'), 'projects', ['project_key'], unique=True)
    op.create_table('error_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_id'), 'error_events', ['id'], unique=False)
    op.create_index(op.f('ix_error_events_status_code'), 'error_events', ['status_code'], unique=False)
    op.create_index(op.f('ix_error_events_timestamp'), 'error_events', ['timestamp'], unique=False)
    op.create_table('error_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_event_id', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['error_event_id'], ['error_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_analysis_error_event_id'), 'error_analysis', ['error_event_id'], unique=True)
    op.create_index(op.f('ix_error_analysis_id'), 'error_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_analysis_id'), table_name='error_analysis')
    op.drop_index(op.f('ix_error_analysis_error_event_id'), table_name='error_analysis')
    op.drop_table('error_analysis')
    op.drop_index(op.f('ix_error_events_timestamp'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_status_code'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_id'), table_name='error_events')
    op.drop_table('error_events')
    op.drop_index(op.f('ix_projects_project_key'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###

